### ISSUE TITLE
in normal mode 'd' deletes a line, expeted behavior to be identical to neovim where 'dd' deletes a line

### ISSUE THREAD

**Issue by Wouterbeets** [dzhou121/gonvim#9]

**Comment by tjdevries** [comment]
@dzhou121 I think this one can be solved with the new `nvim_get_mode`. It doesn't seem that you're handling those events. You might want to look at actualvim and see how they do that.

**Comment by dzhou121** [comment]
@tjdevries Thanks for pointing out. What kind of events am I missing?

**Comment by tjdevries** [comment]
I think it's something with this: https://github.com/lunixbochs/ActualVim/blob/7344157588820ba7d2e982e786bedbda6e000466/neo.py#L294-L313

You can detect when neovim is waiting for more input I think. the function is `nvim_get_mode()`.

Maybe @lunixbochs can explain more (if he feels so inclined :) )

**Comment by lunixbochs** [comment]
Don't call buf_get_lines (or maybe any blocking call) if neovim might be in a weird state. I've worked around this by hard coding "half keys" (see top of neo.py) and keeping a basic state machine.

If you're using callbacks for everything instead of blocking calls, you don't need get_mode, just the half keys hack. Otherwise let me know and I can explain the get_mode state machine (it will improve UI latency)

**Comment by dzhou121** [comment]
Please try the latest Gonvim release. This should be fixed.
